[package]
name= "programming-language"
version= "0.0.0"
description= "Tools including linters, compiler api, language server api and more... for the x7cFClarity Programming Language"
edition= "2021"

[dependencies]